SELECT ugu.USER_ID, ugu.NICKNAME,
CONCAT(ugu.CITY, " ", ugu.STREET_ADDRESS1, " ", ugu.STREET_ADDRESS2) AS '전체주소',
CONCAT(LEFT(ugu.TLNO, 3), "-", MID(ugu.TLNO, 4, 4), "-", RIGHT(ugu.TLNO, 4)) AS '전화번호'
FROM USED_GOODS_BOARD ugb JOIN USEd_GOODS_USER ugu ON ugb.WRITER_ID = ugu.USER_ID
GROUP BY ugb.WRITER_ID HAVING COUNT(ugb.WRITER_ID) >= 3
ORDER BY ugu.USER_ID DESC